"""add is_favorite to user_games

Revision ID: 0dbc0fb80336
Revises: 1063e65caf7b
Create Date: 2026-04-05 14:36:00.798700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dbc0fb80336'
down_revision: Union[str, Sequence[str], None] = '1063e65caf7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_games', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_games', 'is_favorite')
    # ### end Alembic commands ###
