"""add game_genres to user_games

Revision ID: 9d91893d8658
Revises: 40fea1d5f1c9
Create Date: 2026-04-09 19:34:53.537077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d91893d8658'
down_revision: Union[str, Sequence[str], None] = '40fea1d5f1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_games', sa.Column('game_genres', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_games', 'game_genres')
    # ### end Alembic commands ###
