"""remove bio and avatar_url from users

Revision ID: c9e78746f999
Revises: 8b399be6d676
Create Date: 2026-04-10 21:25:58.042856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e78746f999'
down_revision: Union[str, Sequence[str], None] = '8b399be6d676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
